name: certora-bug-injection

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  list-confs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo ::set-output name=matrix::$(ls certora/conf/*_verified.conf | jq -Rsc 'split("\n")[:-1]')

  list-patches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo ::set-output name=matrix::$(ls certora/tests/certora/*.patch | jq -Rsc 'split("\n")[:-1]')

  verify:
    runs-on: ubuntu-latest
    needs: 
        - list-confs
        - list-patches
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check key
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        run: echo "key length" ${#CERTORAKEY}

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora cli
        run: pip install certora-cli
      
      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.10

      - name: Install npm packages
        run: npm i

      - name: Verify rule ${{ matrix.rule }}
        run: |	          
          git apply --allow-empty ${{ matrix.patch }}
          certoraRun ${{ matrix.rule }}
          
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
          
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        patch: ${{ fromJson(needs.list-patches.outputs.matrix) }} 
        rule:
            - certora/conf/verifyRewardsController_verified.conf --rules setTransferStrategyUnitTest setRewardOracleUnitTest setClaimerUnitTest claimAllRewards_should_revert claimAllRewardsOnBehalf_should_revert claimRewards_should_revert claimRewardsOnBehalf_should_revert setTransferStrategy_should_revert setRewardOracle_should_revert  claimAllRewards_unit_test claimAllRewards_should_update_index_data claimAllRewards_should_increase_reward_balance
            - certora/conf/verifyRewardsController_verified.conf --rules configureAssets_unit_test configureAssets_updates_asset_list configureAssets_updates_reward_list configureAssets_updates_available_rewards handleAction_unit_test last_update_time_only_increases claimed_amount_LEQ_accured_rewards
            - certora/conf/verifyRewardsController_verified.conf --rules getUserRewards_unit_test getAssetIndex_uint_test claimRewardsSingle only_emission_manager_can_change only_claim_functions_can_decrease_accrued_rewards